workflows:
    android-workflow:
        name: Android Workflow
        instance_type: mac_mini_m1
        max_build_duration: 120
        environment:
            flutter: stable 
        scripts:
          - name: Set up local.properties
            script: | 
                xcode-project use-profiles
          - name: Get Flutter packages
            script: | 
                flutter packages pub get
          - name: Flutter analyze
            script: | 
                flutter analyze
          - name: Flutter unit tests
            script: | 
                flutter test
            ignore_failure: false
          - name: Build AAB with Flutter
            script: | 
                flutter build appbundle --release        
    ios-workflow:
        name: iOS Workflow
        instance_type: mac_mini_m1
        max_build_duration: 120
        environment:
            flutter: stable  
        scripts:
          - name: Set up code signing settings on Xcode project
            script: | 
                xcode-project use-profiles
          - name: Get Flutter packages
            script: | 
                flutter packages pub get
          - name: Install pods
            script: | 
                find . -name "Podfile" -execdir pod install \;
          - name: Flutter analyze
            script: | 
                flutter analyze
          - name: Flutter unit tests
            script: | 
                flutter test
            ignore_failure: false
          - name: Flutter build ipa
            script: | 
                flutter build ipa --release 
                
                    