workflows:
    android-workflow:
        name: Android Workflow
        instance_type: mac_mini_m1
        max_build_duration: 120
        environment:
            flutter: stable    
    ios-workflow:
        name: iOS Workflow
        instance_type: mac_mini_m1
        max_build_duration: 120 
        scripts:
          - name: Set up local.properties
            script: | 
                xcode-project use-profiles
          - name: Get Flutter packages
            script: | 
                flutter packages pub get
          - name: Flutter analyze
            script: | 
                flutter analyze
          - name: Flutter unit tests
            script: | 
                flutter test
            ignore_failure: true
          - name: Build AAB with Flutter
            script: | 
                flutter build appbundle --release 
                    