workflows:
    android-workflow:
        name: Android Workflow
        instance_type: mac_mini_m1
        max_build_duration: 120
        environment:
            flutter: stable 
        scripts:
           - name: Set up local.properties
             script: | 
                echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
           - name: Get Flutter packages
             script: | 
                flutter packages pub get
           - name: Flutter analyze
             script: | 
                flutter analyze
           - name: Flutter unit tests
             script: | 
                flutter test
             ignore_failure: true
           - name: Build AAB with Flutter
             script: | 
              flutter build appbundle --release \
              --build-name=1.0.$BUILD_NUMBER \
              --build-number=$BUILD_NUMBER     
               
    ios-workflow:
        name: iOS Workflow
        instance_type: mac_mini_m1
        max_build_duration: 120
        environment:
            flutter: stable
            xcode: 15.0 
            cocoapods: default
            # ios_signing:
            #   distribution_type: app_store 
            #   bundle_identifier: com.redstone.store.app 
            # vars:
            #   APP_ID: RVPCR86QJ7.com.redstone.store.app  
        # cache:
        #       cache_paths:
        #         - ~/.cocoapods/repos
        #         - ~/.cache/dart-sdk
        #         - ~/.pub-cache
        # triggering:
        #   events:
        #      - push        
        scripts:  
          - name: Extract app version and build number
            script: |
              build_name=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f 1 | tr -d ' ')

              if [[ -z "$(grep '+' pubspec.yaml)" ]]; then
                build_number="0"
              else
                build_number=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f 2 | tr -d ' ')
              fi

              --export BUILD_NAME=$build_name
              --export BUILD_NUMBER=$build_number

              echo "Build Name: $BUILD_NAME"
              echo "Build Number: $BUILD_NUMBER"
           
          - name: Set up code signing settings on Xcode project
            script: | 
                xcode-project use-profiles
          - name: Get Flutter packages
            script: | 
                flutter packages pub get
          - name: Install pods
            script: | 
                find . -name "Podfile" -execdir pod install \;
          # - name: Flutter analyze
          #   script: | 
          #       flutter analyze
          # - name: Flutter unit tests
          #   script: | 
          #       flutter test
            ignore_failure: false
          - name: Flutter build ipa
            script: | 
              flutter build ipa --release \
               --build-name= $BUILD_NAME \
               --build-number= $BUILD_NUMBER \
               --export-options-plist=/Users/builder/export_options.plist
        artifacts:
                - build/ios/ipa/*.ipa
                - /tmp/xcodebuild_logs/*.log
                - flutter_drive.log 
        # integrations:
        #   app_store_connect: CICD  # Name of API key in codemagic
          
        # publishing: 
        #   app_store_connect:
        #     auth: integration
        #     submit_to_testflight: true        
                
                    