workflows:
    android-workflow:
        name: Android Workflow
        instance_type: mac_mini_m1
        max_build_duration: 120
        environment:
            flutter: stable 
         
        scripts:
           - name: Set up local.properties
             script: | 
                echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
           - name: Get Flutter packages
             script: | 
                flutter packages pub get
           - name: Flutter analyze
             script: | 
                flutter analyze
           - name: Flutter unit tests
             script: | 
                flutter test
             ignore_failure: true
           - name: Build AAB with Flutter
             script: | 
              flutter build appbundle --release \
              --build-name=1.0.$BUILD_NUMBER \
              --build-number=$BUILD_NUMBER     
               
    ios-workflow:
        name: iOS Workflow
        instance_type: mac_mini_m1
        max_build_duration: 120
        environment:
            flutter: stable
            xcode: 15.0 
            cocoapods: default
            
            # ios_signing:
            #   distribution_type: app_store 
            #   bundle_identifier: com.redstone.store.app 
           # vars:
              #APP_ID: RVPCR86QJ7.com.redstone.store.app  
              # BUILD_NAME: true
              # BUILD_NUMBER: true
        # cache:
        #       cache_paths:
        #         - ~/.cocoapods/repos
        #         - ~/.cache/dart-sdk
        #         - ~/.pub-cache    




        # triggering:
        #   events:
        #      - pull_request
        #   branch_patterns:
        #       - pattern: 'master'
        #         include: true
        triggering:
          events:
            - pull_request
          branch_patterns:
          - pattern: "*"
            include: true

        scripts:  
          - name: Check merge target branch, status, type, source branch, and closed status
            script: |
              target_branch=$(git log -n 1 --pretty=%B | grep -Eo "Merge pull request #[0-9]+ into (.*)")
              merge_status=$(git log -n 1 --pretty=%B | grep -Eo "(?<=merged\s+)(success|failure)")
              commit_type=$(git log -n 1 --pretty=%B | grep -i "merge commit")
              source_branch=$(git log -n 1 --pretty=%B | grep -Eo "from\s+(.*?) ")
              is_closed=$(git log -n 1 --pretty=%B | grep -Eo "Closed pull request #[0-9]+")
              if [ "$target_branch" != "master" ]; then
                echo "Skipping build as this is not a merge into master."
                exit 0
              elif [ -z "$commit_type" ]; then
                echo "Skipping build as this is not a merge commit."
                exit 0
              elif [ "$merge_status" != "success" ]; then
                echo "Skipping build as the merge into master was not successful."
                exit 0
              elif [ "$source_branch" == "master" ]; then
                echo "Skipping build as this is a push directly to master, not a merge."
                exit 0
              elif [ -z "$is_closed" ]; then
                echo "Skipping build as the pull request is not yet closed."
                exit 0
              fi
              echo "Successful merge into master from $source_branch, triggering build."  
            
          - name: Set up code signing settings on Xcode project
            script: | 
                xcode-project use-profiles
          - name: Get Flutter packages
            script: | 
                flutter packages pub get
          - name: Install podsa
            script: | 
                find . -name "Podfile" -execdir pod install \;
          # - name: Flutter analyze
          #   script: | 
          #       flutter analyze
          # - name: Flutter unit tests
          #   script: | 
          #       flutter test
          ## hello    
            ignore_failure: false
          - name: Flutter build ipa
            script: | 
              export BUILD_NAME=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f 1 | tr -d ' ')

                if [[ -z "$(grep '+' pubspec.yaml)" ]]; then
                  export  BUILD_NUMBER="0"
                else
                  export BUILD_NUMBER=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d '+' -f 2 | tr -d ' ')
                fi

              flutter build ipa --release \
               --build-name=$BUILD_NAME \
               --build-number=$BUILD_NUMBER \
               --export-options-plist=/Users/builder/export_options.plist
        artifacts:
                - build/ios/ipa/*.ipa
                - /tmp/xcodebuild_logs/*.log
                - flutter_drive.log 
        # integrations:
        #   app_store_connect: CICD  # Name of API key in codemagic
          
        # publishing: 
        #   app_store_connect:
        #     auth: integration
        #     submit_to_testflight: true        
                
                    